import { MoodScale } from "@/types/mood";

export const moodScale: MoodScale[] = [
    {
        value: 0,
        label: "Elated",
        description: "Overjoyed, unstoppable energy",
        color: "text-indigo-600 dark:text-indigo-400",
        bg: "bg-indigo-100 dark:bg-indigo-900/30",
    },
    {
        value: 1,
        label: "Very Happy",
        description: "High spirits, confident and upbeat",
        color: "text-blue-600 dark:text-blue-400",
        bg: "bg-blue-100 dark:bg-blue-900/30",
    },
    {
        value: 2,
        label: "Good",
        description: "Content, minor worries fade quickly",
        color: "text-sky-600 dark:text-sky-400",
        bg: "bg-sky-100 dark:bg-sky-900/30",
    },
    {
        value: 3,
        label: "Positive",
        description: "Generally fine, occasional stress",
        color: "text-cyan-600 dark:text-cyan-400",
        bg: "bg-cyan-100 dark:bg-cyan-900/30",
    },
    {
        value: 4,
        label: "Okay",
        description: "Some good moments, average day",
        color: "text-teal-600 dark:text-teal-400",
        bg: "bg-teal-100 dark:bg-teal-900/30",
    },
    {
        value: 5,
        label: "Neutral",
        description: "Neither good nor bad",
        color: "text-slate-600 dark:text-slate-400",
        bg: "bg-slate-100 dark:bg-slate-800",
    },
    {
        value: 6,
        label: "Low",
        description: "Motivation dipping; tasks feel harder",
        color: "text-yellow-600 dark:text-yellow-400",
        bg: "bg-yellow-100 dark:bg-yellow-900/30",
    },
    {
        value: 7,
        label: "Struggling",
        description: "Intense distress; trouble reaching out",
        color: "text-amber-600 dark:text-amber-400",
        bg: "bg-amber-100 dark:bg-amber-900/30",
    },
    {
        value: 8,
        label: "Overwhelmed",
        description: "Unable to function; tasks feel impossible",
        color: "text-orange-600 dark:text-orange-400",
        bg: "bg-orange-100 dark:bg-orange-900/30",
    },
    {
        value: 9,
        label: "Crisis",
        description: "Strong urge to end life; thoughts of action",
        color: "text-red-600 dark:text-red-400",
        bg: "bg-red-100 dark:bg-red-900/30",
    },
    {
        value: 10,
        label: "Emergency",
        description: "Taking steps toward self-harm",
        color: "text-rose-700 dark:text-rose-400",
        bg: "bg-rose-200 dark:bg-rose-900/40",
    },
];