import type { MoodScale } from "@/types/mood";

// Soft Organic aesthetic - warm, natural tones
// Light mode: warm creams and earth tones - watercolor washes on paper
// Dark mode: warm botanical ink with hue-identity washes.
//   Each family preserves its character (sage / dusk / sand / coral) without
//   collapsing into blackened chips or over-saturated emergency blocks.
export const moodScale: MoodScale[] = [
    {
        value: 0,
        label: "Elated",
        description: "Overjoyed, unstoppable energy",
        color: "text-sage-600",
        bg: "bg-sage-100",
        borderColor: "#A8C5A8",
        bgHex: "#E8EFE8",
        textHex: "#476D47",
        bgHexDark: "#1F3326",
        textHexDark: "#CBE4C4",
    },
    {
        value: 1,
        label: "Very Happy",
        description: "High spirits, confident and upbeat",
        color: "text-sage-600",
        bg: "bg-sage-50",
        borderColor: "#D1DFD1",
        bgHex: "#F4F7F4",
        textHex: "#476D47",
        bgHexDark: "#22372A",
        textHexDark: "#C5E0BE",
    },
    {
        value: 2,
        label: "Good",
        description: "Content, minor worries fade quickly",
        color: "text-sage-600",
        bg: "bg-sage-50",
        borderColor: "#D1DFD1",
        bgHex: "#F4F7F4",
        textHex: "#476D47",
        bgHexDark: "#263B2D",
        textHexDark: "#BED9B8",
    },
    {
        value: 3,
        label: "Positive",
        description: "Generally fine, occasional stress",
        color: "text-dusk-600",
        bg: "bg-dusk-100",
        borderColor: "#DDD8E5",
        bgHex: "#EFECF2",
        textHex: "#695C78",
        bgHexDark: "#2D2940",
        textHexDark: "#D8D0E4",
    },
    {
        value: 4,
        label: "Okay",
        description: "Some good moments, average day",
        color: "text-dusk-600",
        bg: "bg-dusk-50",
        borderColor: "#EFECF2",
        bgHex: "#F8F7F9",
        textHex: "#6B5C7A",
        bgHexDark: "#302B3E",
        textHexDark: "#CEC4DC",
    },
    {
        value: 5,
        label: "Neutral",
        description: "Neither good nor bad",
        color: "text-sand-700",
        bg: "bg-sand-100",
        borderColor: "#E5D9BF",
        bgHex: "#F9F5ED",
        textHex: "#7A6545",
        bgHexDark: "#3A2D1D",
        textHexDark: "#E8D19C",
    },
    {
        value: 6,
        label: "Low",
        description: "Motivation dipping; tasks feel harder",
        color: "text-sand-700",
        bg: "bg-sand-50",
        borderColor: "#F2EBD9",
        bgHex: "#FDFBF7",
        textHex: "#7A6545",
        bgHexDark: "#422C18",
        textHexDark: "#E5C583",
    },
    {
        value: 7,
        label: "Struggling",
        description: "Intense distress; trouble reaching out",
        color: "text-coral-700",
        bg: "bg-coral-100",
        borderColor: "#FACFC7",
        bgHex: "#FDE8E4",
        textHex: "#A84334",
        bgHexDark: "#4A2119",
        textHexDark: "#F3BAAD",
    },
    {
        value: 8,
        label: "Overwhelmed",
        description: "Unable to function; tasks feel impossible",
        color: "text-coral-700",
        bg: "bg-coral-50",
        borderColor: "#FDE8E4",
        bgHex: "#FEF6F4",
        textHex: "#A84334",
        bgHexDark: "#4D1E18",
        textHexDark: "#F0B1A4",
    },
    {
        value: 9,
        label: "Crisis",
        description: "Strong urge to end life; thoughts of action",
        color: "text-coral-700",
        bg: "bg-coral-100",
        borderColor: "#FACFC7",
        bgHex: "#FDE8E4",
        textHex: "#A84334",
        bgHexDark: "#511B15",
        textHexDark: "#EFA99B",
    },
    {
        value: 10,
        label: "Emergency",
        description: "Taking steps toward self-harm",
        color: "text-coral-800",
        bg: "bg-coral-200",
        borderColor: "#F5A899",
        bgHex: "#FACFC7",
        textHex: "#9D3D30",
        bgHexDark: "#561913",
        textHexDark: "#EFA99B",
    },
];
