import { MoodScale } from "@/types/mood";

// Soft Organic aesthetic - warm, natural tones
// Light mode: warm creams and earth tones
// Dark mode: deep warm browns
export const moodScale: MoodScale[] = [
    {
        value: 0,
        label: "Elated",
        description: "Overjoyed, unstoppable energy",
        color: "text-sage-600",
        bg: "bg-sage-100",
        borderColor: "#A8C5A8",
        bgHex: "#E8EFE8",
        textHex: "#476D47",
        bgHexDark: "#2D3D2D",
        textHexDark: "#A8C5A8",
    },
    {
        value: 1,
        label: "Very Happy",
        description: "High spirits, confident and upbeat",
        color: "text-sage-500",
        bg: "bg-sage-50",
        borderColor: "#D1DFD1",
        bgHex: "#F4F7F4",
        textHex: "#5B8A5B",
        bgHexDark: "#283328",
        textHexDark: "#7BA87B",
    },
    {
        value: 2,
        label: "Good",
        description: "Content, minor worries fade quickly",
        color: "text-sage-400",
        bg: "bg-sage-50",
        borderColor: "#D1DFD1",
        bgHex: "#F4F7F4",
        textHex: "#7BA87B",
        bgHexDark: "#252D25",
        textHexDark: "#A8C5A8",
    },
    {
        value: 3,
        label: "Positive",
        description: "Generally fine, occasional stress",
        color: "text-dusk-500",
        bg: "bg-dusk-100",
        borderColor: "#DDD8E5",
        bgHex: "#EFECF2",
        textHex: "#695C78",
        bgHexDark: "#2D2A33",
        textHexDark: "#C4BBCF",
    },
    {
        value: 4,
        label: "Okay",
        description: "Some good moments, average day",
        color: "text-dusk-400",
        bg: "bg-dusk-50",
        borderColor: "#EFECF2",
        bgHex: "#F8F7F9",
        textHex: "#847596",
        bgHexDark: "#28252D",
        textHexDark: "#A396B3",
    },
    {
        value: 5,
        label: "Neutral",
        description: "Neither good nor bad",
        color: "text-sand-600",
        bg: "bg-sand-100",
        borderColor: "#E5D9BF",
        bgHex: "#F9F5ED",
        textHex: "#9D8660",
        bgHexDark: "#302A22",
        textHexDark: "#D4C4A0",
    },
    {
        value: 6,
        label: "Low",
        description: "Motivation dipping; tasks feel harder",
        color: "text-sand-500",
        bg: "bg-sand-50",
        borderColor: "#F2EBD9",
        bgHex: "#FDFBF7",
        textHex: "#BDA77D",
        bgHexDark: "#352D22",
        textHexDark: "#D4C4A0",
    },
    {
        value: 7,
        label: "Struggling",
        description: "Intense distress; trouble reaching out",
        color: "text-coral-500",
        bg: "bg-coral-100",
        borderColor: "#FACFC7",
        bgHex: "#FDE8E4",
        textHex: "#E06B55",
        bgHexDark: "#3D2822",
        textHexDark: "#F5A899",
    },
    {
        value: 8,
        label: "Overwhelmed",
        description: "Unable to function; tasks feel impossible",
        color: "text-coral-500",
        bg: "bg-coral-50",
        borderColor: "#FDE8E4",
        bgHex: "#FEF6F4",
        textHex: "#E06B55",
        bgHexDark: "#3A2520",
        textHexDark: "#ED8370",
    },
    {
        value: 9,
        label: "Crisis",
        description: "Strong urge to end life; thoughts of action",
        color: "text-coral-600",
        bg: "bg-coral-100",
        borderColor: "#FACFC7",
        bgHex: "#FDE8E4",
        textHex: "#C75441",
        bgHexDark: "#3D221D",
        textHexDark: "#E06B55",
    },
    {
        value: 10,
        label: "Emergency",
        description: "Taking steps toward self-harm",
        color: "text-coral-600",
        bg: "bg-coral-200",
        borderColor: "#F5A899",
        bgHex: "#FACFC7",
        textHex: "#C75441",
        bgHexDark: "#401F1A",
        textHexDark: "#ED8370",
    },
];
